export const packageHistoryMock = {
  '16.6.3': {
    dependencyCount: 4,
    dependencySizes: [{ approximateSize: 6077, name: 'react' }],
    description: 'React is a JavaScript library for building user interfaces.',
    gzip: 2577,
    hasJSModule: false,
    hasJSNext: false,
    hasSideEffects: true,
    name: 'react',
    repository: 'https://github.com/facebook/react',
    scoped: false,
    size: 6070,
    version: '16.6.3'
  },
  '16.7.0': {
    dependencyCount: 4,
    dependencySizes: [{ approximateSize: 6069, name: 'react' }],
    description: 'React is a JavaScript library for building user interfaces.',
    gzip: 2572,
    hasJSModule: false,
    hasJSNext: false,
    hasSideEffects: true,
    name: 'react',
    repository: 'https://github.com/facebook/react',
    scoped: false,
    size: 6062,
    version: '16.7.0'
  },
  '16.8.0': {
    dependencyCount: 4,
    dependencySizes: [{ approximateSize: 6663, name: 'react' }],
    description: 'React is a JavaScript library for building user interfaces.',
    gzip: 2721,
    hasJSModule: false,
    hasJSNext: false,
    hasSideEffects: true,
    name: 'react',
    repository: 'https://github.com/facebook/react',
    scoped: false,
    size: 6652,
    version: '16.8.0'
  },
  '16.8.1': {
    dependencyCount: 4,
    dependencySizes: [{ approximateSize: 6663, name: 'react' }],
    description: 'React is a JavaScript library for building user interfaces.',
    gzip: 2721,
    hasJSModule: false,
    hasJSNext: false,
    hasSideEffects: true,
    name: 'react',
    repository: 'https://github.com/facebook/react',
    scoped: false,
    size: 6652,
    version: '16.8.1'
  },
  '16.8.2': {
    dependencyCount: 4,
    dependencySizes: [{ approximateSize: 6663, name: 'react' }],
    description: 'React is a JavaScript library for building user interfaces.',
    gzip: 2721,
    hasJSModule: false,
    hasJSNext: false,
    hasSideEffects: true,
    name: 'react',
    repository: 'https://github.com/facebook/react',
    scoped: false,
    size: 6652,
    version: '16.8.2'
  },
  '16.8.3': {
    dependencyCount: 4,
    dependencySizes: [{ approximateSize: 6663, name: 'react' }],
    description: 'React is a JavaScript library for building user interfaces.',
    gzip: 2721,
    hasJSModule: false,
    hasJSNext: false,
    hasSideEffects: true,
    name: 'react',
    repository: 'https://github.com/facebook/react',
    scoped: false,
    size: 6652,
    version: '16.8.3'
  },
  '16.8.4': {
    dependencyCount: 4,
    dependencySizes: [{ approximateSize: 6663, name: 'react' }],
    description: 'React is a JavaScript library for building user interfaces.',
    gzip: 2721,
    hasJSModule: false,
    hasJSNext: false,
    hasSideEffects: true,
    name: 'react',
    repository: 'https://github.com/facebook/react',
    scoped: false,
    size: 6652,
    version: '16.8.4'
  },
  '16.8.5': {
    dependencyCount: 4,
    dependencySizes: [{ approximateSize: 6663, name: 'react' }],
    description: 'React is a JavaScript library for building user interfaces.',
    gzip: 2721,
    hasJSModule: false,
    hasJSNext: false,
    hasSideEffects: true,
    name: 'react',
    repository: 'https://github.com/facebook/react',
    scoped: false,
    size: 6652,
    version: '16.8.5'
  },
  '16.8.6': {
    dependencyCount: 4,
    dependencySizes: [{ approximateSize: 6663, name: 'react' }],
    description: 'React is a JavaScript library for building user interfaces.',
    gzip: 2720,
    hasJSModule: false,
    hasJSNext: false,
    hasSideEffects: true,
    name: 'react',
    repository: 'https://github.com/facebook/react',
    scoped: false,
    size: 6652,
    version: '16.8.6'
  },
  '16.9.0': {
    dependencyCount: 3,
    dependencySizes: [{ approximateSize: 6674, name: 'react' }],
    description: 'React is a JavaScript library for building user interfaces.',
    gzip: 2721,
    hasJSModule: false,
    hasJSNext: false,
    hasSideEffects: true,
    name: 'react',
    repository: 'https://github.com/facebook/react',
    scoped: false,
    size: 6666,
    version: '16.9.0'
  },
  '16.10.0': {
    assets: [{ gzip: 2700, name: 'main', size: 6675, type: 'js' }],
    dependencyCount: 3,
    dependencySizes: [{ approximateSize: 6683, name: 'react' }],
    description: 'React is a JavaScript library for building user interfaces.',
    gzip: 2700,
    hasJSModule: false,
    hasJSNext: false,
    hasSideEffects: true,
    name: 'react',
    repository: 'https://github.com/facebook/react',
    scoped: false,
    size: 6675,
    version: '16.10.0'
  },
  '16.10.1': {
    assets: [{ gzip: 2699, name: 'main', size: 6675, type: 'js' }],
    dependencyCount: 3,
    dependencySizes: [{ approximateSize: 6683, name: 'react' }],
    description: 'React is a JavaScript library for building user interfaces.',
    gzip: 2699,
    hasJSModule: false,
    hasJSNext: false,
    hasSideEffects: true,
    name: 'react',
    repository: 'https://github.com/facebook/react',
    scoped: false,
    size: 6675,
    version: '16.10.1'
  },
  '16.10.2': {
    assets: [{ gzip: 2699, name: 'main', size: 6675, type: 'js' }],
    dependencyCount: 3,
    dependencySizes: [{ approximateSize: 6683, name: 'react' }],
    description: 'React is a JavaScript library for building user interfaces.',
    gzip: 2699,
    hasJSModule: false,
    hasJSNext: false,
    hasSideEffects: true,
    name: 'react',
    repository: 'https://github.com/facebook/react.git',
    scoped: false,
    size: 6675,
    version: '16.10.2'
  },
  '16.11.0': {
    assets: [{ gzip: 2630, name: 'main', size: 6499, type: 'js' }],
    dependencyCount: 3,
    dependencySizes: [{ approximateSize: 6503, name: 'react' }],
    description: 'React is a JavaScript library for building user interfaces.',
    gzip: 2630,
    hasJSModule: false,
    hasJSNext: false,
    hasSideEffects: true,
    name: 'react',
    repository: 'https://github.com/facebook/react.git',
    scoped: false,
    size: 6499,
    version: '16.11.0'
  },
  '0.0.0-experimental-5faf377df': {}
};
